# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudLens < Formula
  desc ""
  homepage "https://github.com/one2nc/cloud-lens"
  version "0.1.10"

  on_macos do
    url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.10/cloud-lens_0.1.10_darwin_all.tar.gz"
    sha256 "3ff4e25d51f1ac0b39ff46a0ef52609b4b1763f3addf4f36e0d4ff1b3790dacf"

    def install
      bin.install "cloud-lens"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.10/cloud-lens_0.1.10_linux_armv6.tar.gz"
      sha256 "c28a085638b5598ee2734e73a12825e7b1ac96c65003501977161d4e8f9ceeea"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.10/cloud-lens_0.1.10_linux_amd64.tar.gz"
      sha256 "aff0a8e227ee591fc4727305ae1a61e4b5cc1ad9c015fc6fda325ccc049a7180"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.10/cloud-lens_0.1.10_linux_arm64.tar.gz"
      sha256 "3d16897090651268e905afeb33a6408b89e7720c6eecb59b085b6a1a3c5ab6ab"

      def install
        bin.install "cloudlens"
      end
    end
  end
end
