# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudlens < Formula
  desc ""
  homepage "https://github.com/one2nc/cloudlens"
  version "0.1.0"

  on_macos do
    url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0/cloudlens_0.1.0_darwin_all.tar.gz"
    sha256 "a3868c560384fd79080cdcfed7c1b9d9285dc64d90f35070c1a314c5914bd05d"

    def install
      bin.install "cloudlens"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0/cloudlens_0.1.0_linux_arm64.tar.gz"
      sha256 "2caa942a538f80bb9ed0896172a2ed8019e1f7eb74907bb907faa56f2d6d11ff"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0/cloudlens_0.1.0_linux_amd64.tar.gz"
      sha256 "7685879202a057f837728935cc7a742a02ef1b1046e8b9956da3cb0d5ed33a8e"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0/cloudlens_0.1.0_linux_armv6.tar.gz"
      sha256 "8cbc6ce84973cba6d270f5c2810ac2ad8064a3f3fc5a430f0f2f915e6fb1a706"

      def install
        bin.install "cloudlens"
      end
    end
  end
end
