# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudLens < Formula
  desc ""
  homepage "https://github.com/one2nc/cloud-lens"
  version "0.1.9"

  on_macos do
    url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.9/cloud-lens_0.1.9_darwin_all.tar.gz"
    sha256 "961797ea8082eb3cd1ca5f598575326af8d0eae40010b695aa3c2699eef9ff1e"

    def install
      bin.install "cloud-lens"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.9/cloud-lens_0.1.9_linux_arm64.tar.gz"
      sha256 "2e3c5fea085e8afc9672829c458334a91550e49ffc89f2133d7d6f4c4d1c75ee"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.9/cloud-lens_0.1.9_linux_amd64.tar.gz"
      sha256 "525842785b96e3af82a6710e9cba79ae2d93d035ae73105c92bdf66ce966ad3a"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.9/cloud-lens_0.1.9_linux_armv6.tar.gz"
      sha256 "4f1692d07a645e399d3175bc2652fa396d72b570d78addeee308a55fd0e1c41f"

      def install
        bin.install "cloudlens"
      end
    end
  end
end
