# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudlens < Formula
  desc ""
  homepage "https://github.com/one2nc/cloudlens"
  version "0.1.0-rc.4"

  on_macos do
    url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0-rc.4/cloudlens_0.1.0-rc.4_darwin_all.tar.gz"
    sha256 "6cac52a3c1a1c060fee5f3b8282d5f8b6b1a4844af4dcd700e19ca1a7cb071b6"

    def install
      bin.install "cloudlens"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0-rc.4/cloudlens_0.1.0-rc.4_linux_arm64.tar.gz"
      sha256 "3d4aec8445efd8a65e5faa76c8d1518e56f30064f02178502a4c7824682d64ef"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0-rc.4/cloudlens_0.1.0-rc.4_linux_amd64.tar.gz"
      sha256 "bb48f7f91f701d02508b4a068fc26b2bf9d7ff7df8d7739ad2106a534b6c93bd"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0-rc.4/cloudlens_0.1.0-rc.4_linux_armv6.tar.gz"
      sha256 "3042966ae98320568b689b53c8d01174279e7fbc077bbbfac9cf7f45c04765dc"

      def install
        bin.install "cloudlens"
      end
    end
  end
end
