# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudLens < Formula
  desc ""
  homepage "https://github.com/one2nc/cloud-lens"
  version "0.1.11"

  on_macos do
    url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.11/cloud-lens_0.1.11_darwin_all.tar.gz"
    sha256 "e531900e8c7cdb55995ecafdb2c166a29a769d90d16445ddf41c9b9776de423f"

    def install
      bin.install "cloud-lens"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.11/cloud-lens_0.1.11_linux_arm64.tar.gz"
      sha256 "be8b298aa80fffa1856d0c8a5c8f727bb04af4ebdf27689c7db1e4dd0f195753"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.11/cloud-lens_0.1.11_linux_amd64.tar.gz"
      sha256 "4b9917da37bd4b67f5e7b8e5a6ec0db3e1450ebde0f31a670368fe8154a8691b"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloud-lens/releases/download/v0.1.11/cloud-lens_0.1.11_linux_armv6.tar.gz"
      sha256 "5d416d4c1ba3e30f221dac0b5926160dbda41b67ad6f4727a230d6f3f86dca73"

      def install
        bin.install "cloudlens"
      end
    end
  end
end
