# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudlens < Formula
  desc ""
  homepage "https://github.com/one2nc/cloudlens"
  version "0.1.0"

  on_macos do
    url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0/cloudlens_0.1.0_darwin_all.tar.gz"
    sha256 "4c6c81657190dfbcd531f9399e4910077fdefa67fdf81b89919fa45af9bdfad9"

    def install
      bin.install "cloudlens"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0/cloudlens_0.1.0_linux_arm64.tar.gz"
      sha256 "b001d06e187a4c2d0e1f03efb19cbe40ddeeaced3f4d39ff19d6d933052a55f6"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0/cloudlens_0.1.0_linux_amd64.tar.gz"
      sha256 "de21014648942f9cd181d1eb46728c1bd790f1324cbabe202bfae18cc4403e7c"

      def install
        bin.install "cloudlens"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/one2nc/cloudlens/releases/download/v0.1.0/cloudlens_0.1.0_linux_armv6.tar.gz"
      sha256 "3e473ec81f902ed45d3f901dc1d4be0557cce1c4cbb3496d581767438a261073"

      def install
        bin.install "cloudlens"
      end
    end
  end
end
